### ISSUE TITLE
[Question] Can i do cache with this iptv proxy ?

### ISSUE THREAD

**Issue by CyberPoison** [kvaster/iptv-proxy#1]
Hi i'm looking for some way to do cache from a iptv source and proxy it to my Plex server.

The reason to do the cache it's to have less freezes, can you tell me if i can do that with your script ? 

I have nvme ssd, and i would like to do some cache before streaming it there was a way to do that?

**Comment by kvaster** [comment]
No cache for a moment. I'm going to implement this feature, but I don't think it will really help.
I was struggling with freezes (using kodi with simple iptv plugin), but it seems that all iptv systems are trying to stream live tv with really small gap. What helped to me - I've changed tcp congestion control to bbr in linux kernel on my restreaming box.

**Comment by kvaster** [comment]
Also you can enable debug logging in iptv-proxy in order to investigate exact problem with streaming.
