### ISSUE TITLE
P2P Media Loader "not a bug"

### ISSUE THREAD

**Issue by delltrak** [kvaster/iptv-proxy#11]
**Hello Friend**.
i have a situation: I need p2p media loader to load my .m3u8, but that library its in js. 
so, if I create a .html page with video player and load in webview, whit proxy I can send that video to exoplayer ?
your project is kind awesome.

🖖🏻☺️

**Comment by kvaster** [comment]
Telling the truth, I do not understand completely the question. You m3u8 can't be retrieved by direct url and you need to get it via js library ? In this case you'll need to create server app which will do that job and will provide m3u8 playlist for the proxy. This server may be implemented using nodejs (for example) with your library...
