### ISSUE TITLE
Local m3u possible?

### ISSUE THREAD

**Issue by steamyRayV** [kvaster/iptv-proxy#13]
Sorry to be a bother!
I tried using "- url: file:///path/foo.m3u" instead of a web address and it isn't working yet. Is there a way of using a local m3u list?
I'm getting:
"App :: fatal error
java.lang.IllegalArgumentException: invalid URI scheme file"
Thanks again for sharing this.

**Comment by kvaster** [comment]
File urls currently not supported, but it is easy to add support for loading .m3u files from local disk... Why do you need such option ?

**Comment by steamyRayV** [comment]
As this tool stands it will match channels from the same provider but if there's any variation of channel name, it will make multiples of the same channel.
For example, if an American news network were called, "Free Television News," you may see the following logical naming:
"FTN: US"
"US FTN"
"Free Television News"
If I have the option to load m3u from disk, I can automate the renaming to make them match before iptv-proxy parses them.

**Comment by kvaster** [comment]
Usually this is a provider's problem, cause if you have different entries with different names usually it means different channels...

**Comment by kvaster** [comment]
Can you please provide me with example from your m3u file ? (please remove secret parts of the urls inside, but I need to know if they differs).

**Comment by kvaster** [comment]
Anyway I can probably add loading m3u from local disk, but it may be much more usefull to add channel remapping ? This was not usefull for me, cause I need to map m3u channels to xmltv epg data.

**Comment by steamyRayV** [comment]
Provider 1
#EXTINF:-1 tvg-id="FTN.us" tvg-name="US: FTN" tvg-logo="https://domain.com/image/ftn.png" group-title="US-ENTERTAINMENT",US: FTN
http://domain.com/user/pass/2000230
Provider 2
#EXTINF:-1 tvg-id="FTN" tvg-name="FTN US" tvg-logo="http://domain.com:80/images/b.png" group-title="NEWS CHANNELS",FTN US
http://otherdomain.com/user/otherpass/4222

The way they designate the country doesn't match up. It's consistent though for all channels so I was thinking I would just make a script to download the two m3u's then find-and-replace the country references to remove them with 'sed' or something. That seems like it would be easier than adding remapping support to this project. BUT, I am happy to script and that's as far as my skill goes, so I don't really know how hard it would be to add remapping. Thanks for considering this!

**Comment by kvaster** [comment]
Oh. Theese are two different providers. Usually it is not easy to mix them. I will try to do some work on remapping side soon. And will try to add 'local disk m3u' today.

**Comment by steamyRayV** [comment]
Thank you so much. I think I should just learn Java to some extent so I'm not so helpless... But again, thanks for this project.

**Comment by kvaster** [comment]
https://github.com/kvaster/iptv-proxy/commit/5ae37a3de6cb05a3eb3ebf90ca8b1eaca5f21d40
