### ISSUE TITLE
Channel Combining question

### ISSUE THREAD

**Issue by warrentc3** [kvaster/iptv-proxy#14]
What is the matching principle for channel combination?

Does it only combine/HA channels that have the same URL?
Can it combine based on other m3u tags... like tvg-id or something?

**Comment by kvaster** [comment]
Currently it combines channels only by name and only in one server group. And ofcause we can combine them based of m3u tags, but for it was unreliable:

https://github.com/kvaster/iptv-proxy/blob/master/src/main/java/com/kvaster/iptv/IptvProxyService.java#L250
