### ISSUE TITLE
Its runs, but what now..?

### ISSUE THREAD

**Issue by sebastianengman** [kvaster/iptv-proxy#15]
Hi. 

Am I correct that the service will provide a webservice on the port configured in config.yml?

I get everything to run on the machine, but cannot access the service from browser or VLC.

This is what iptv-proxy dumps when starting.

> 
17.07.2023 10:08:52 [INFO ] :: App :: loading config...
17.07.2023 10:08:53 [INFO ] :: IptvProxyService :: starting
17.07.2023 10:08:53 [INFO ] :: IptvProxyService :: updating channels
17.07.2023 10:08:53 [INFO ] :: AsyncLoader :: 00001| loading playlist: iptvteststream, retry: 0, url: http://*********
17.07.2023 10:08:53 [INFO ] :: IptvProxyService :: parsing playlist: iptvteststream, url: http://*********
17.07.2023 10:08:53 [DEBUG] :: HttpUtils :: 00001| ok (739ms)
17.07.2023 10:08:54 [INFO ] :: IptvProxyService :: channels updated
17.07.2023 10:08:54 [INFO ] :: IptvProxyService :: started
<

**Comment by sebastianengman** [comment]
This is my config.yml

host: 127.0.0.1
port: 8080
base_url: http://ubuntu:8080
servers:
  - name: iptvteststream
    connections:
      - url: http://*******
        max_connections: 1
allow_anonymous: true

**Comment by parryhotter007** [comment]
Can you elobrate more on what would be the URL we need to access in the above example?

**Comment by kvaster** [comment]
Above example is misconfigured unless 'ubuntu' is resolved to `127.0.0.1` or you have something like nginx in front of. With base_url above you need to access via:

`http://ubuntu:8080/m3u/<login>` - m3u
`http://ubuntu:8080/epg.xml.gz` - epg if you have one

**Comment by kvaster** [comment]
My proposition is to try following config for you:

```
host: 0.0.0.0
port: 8080
servers:
  name: iptvteststream
  connections:
    url: http://*******
    max_connections: 1
    allow_anonymous: true
```

Omit `base_url` and listen on all interfaces with `0.0.0.0`
And connect via url: `http://<you ip address>:8080/m3u`

**Comment by sebastianengman** [comment]
Any idea why I get this error? 

root@iptvproxy:/iptv-proxy/build/libs# java -Dconfig=config.yml -Dlog.level=debug -jar iptv-proxy-all.jar
15:14:16,742 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:14:16,743 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/iptv-proxy/build/libs/iptv-proxy-all.jar!/logback.xml]
15:14:16,751 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@589b3632 - URL [jar:file:/iptv-proxy/build/libs/iptv-proxy-all.jar!/logback.xml] is not of type file
15:14:16,823 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:14:16,915 |-WARN in ch.qos.logback.core.joran.util.PropertySetter@45f45fa1 - No setter for property [target] in ch.qos.logback.core.joran.conditional.IfAction.
15:14:16,916 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:14:16,919 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
15:14:16,922 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:14:16,979 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.kvaster] to false
15:14:16,979 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - com.kvaster level set to DEBUG
15:14:16,979 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[com.kvaster]
15:14:16,979 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
15:14:16,979 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
15:14:16,979 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:14:16,979 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4c6e276e - Registering current configuration as safe fallback point

03.01.2024 15:14:16 [INFO ] :: App :: loading config...
03.01.2024 15:14:17 [ERROR] :: App :: fatal error
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<com.kvaster.iptv.config.IptvServerConfig>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (File); line: 5, column: 3] (through reference chain: com.kvaster.iptv.config.IptvProxyConfig["servers"])
        at com.kvaster.iptv.ConfigLoader.loadConfig(ConfigLoader.java:28)
        at com.kvaster.iptv.App.main(App.java:18)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<com.kvaster.iptv.config.IptvServerConfig>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (File); line: 5, column: 3] (through reference chain: com.kvaster.iptv.config.IptvProxyConfig["servers"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494)
        at com.kvaster.iptv.ConfigLoader.loadConfig(ConfigLoader.java:26)
        ... 1 common frames omitted
root@iptvproxy:/iptv-proxy/build/libs# java --version
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)
root@iptvproxy:/iptv-proxy/build/libs#

**Comment by kvaster** [comment]
@sebastianengman , looks like your config have an error:

[Source: (File); line: 5, column: 3] -> it seems here (in 'servers' section) you have object instead of array.

Just realized that you have used my snippet. Corrected one:

```
host: 0.0.0.0
port: 8080
servers:
- name: iptvteststream
  connections:
    url: http://*******
    max_connections: 1
    allow_anonymous: true
```

**Comment by sebastianengman** [comment]
> @sebastianengman , looks like your config have an error:
> 
> [Source: (File); line: 5, column: 3] -> it seems here (in 'servers' section) you have object instead of array.
> 
> Just realized that you have used my snippet. Corrected one:
> 
> ```
> host: 0.0.0.0
> port: 8080
> servers:
> - name: iptvteststream
>   connections:
>     url: http://*******
>     max_connections: 1
>     allow_anonymous: true
> ```

Thanks :) 

I found it and deleted my comment but you replied after. Thank you!

**Comment by sebastianengman** [comment]
> > @sebastianengman , looks like your config have an error:
> > [Source: (File); line: 5, column: 3] -> it seems here (in 'servers' section) you have object instead of array.
> > Just realized that you have used my snippet. Corrected one:
> > ```
> > host: 0.0.0.0
> > port: 8080
> > servers:
> > - name: iptvteststream
> >   connections:
> >     url: http://*******
> >     max_connections: 1
> >     allow_anonymous: true
> > ```
> 
> Thanks :)
> 
> I found it and deleted my comment but you replied after. Thank you!

allow_anonymous: true has to be without spaces right? Not under the server section?

**Comment by kvaster** [comment]
allow_anonymous is a global option, not per connection. Sorry for late answer :)
