### ISSUE TITLE
m3u update?

### ISSUE THREAD

**Issue by kedda** [kvaster/iptv-proxy#5]
Any chance this will be updated to work with m3u? 

I worded this terribly! I am sorry. Today it works with HLS (m3u8) streams. I was wondering if you were going to extend it to work with mpeg-ts or m3u streams.

Thanks for replying!

**Comment by kvaster** [comment]
Telling the truth, I don't understand the question :)
This proxy works with m3u :)

**Comment by kedda** [comment]
Question has been updated to make sense!

**Comment by kvaster** [comment]
It should already work with ts streams. I will update docs.
