### ISSUE TITLE
Proxy user cannot contain "-" character

### ISSUE THREAD

**Issue by reinthal** [kvaster/iptv-proxy#6]
#### Steps to reproduce 
1. In the config.yml enter a username containing - character
2. Start the server with the above config
3. Download the m3u file  and open in VLC for example
4. VLC errors out about certificates. 
```   access error: HTTP connection failure
    gnutls error: Certificate verification failure: The certificate is NOT trusted. The certificate chain uses expired certificate.
```

where my-username is a username containing - charater

#### Current behaviour (bug)

Server fails to verify the digest. Reason for bug is that - characters result in incorrect splitting of data, see line 375 in `src/main/java/com/kvaster/iptv/IptvProxyService.java`

#### Expected behavior (correct)
digest is correctly validated even when containing -, alternatively, error on server startup when usernames contain - characters.

#### Relevant logs and/or media (optional)

Server log row
`08.12.2021 06:10:50 [WARN ] :: IptvProxyService :: invalid user token: my-username-cd263115950df845402b7f8775e851f4, proxyUser: null `

**Comment by kvaster** [comment]
Should be fixed now

**Comment by reinthal** [comment]
Thanks! : )
