### ISSUE TITLE
Server redirect does not respect server port and protocol

### ISSUE THREAD

**Issue by reinthal** [kvaster/iptv-proxy#7]
#### Issue description

When attempting to fetch channel stream the server redirects to port 80 with protocol http.  The redirect fails as port 80 is not open.

### Environment 
vanilla nginx listening on port 27016 https and java sdk 18

#### Steps to reproduce the issue

1. Successfully fetch the playlist file 
2. open in vlc.
3. VLC errors out and asks me to check logs

#### What's the expected result?

Server redirect respects protocol and port

#### What's the actual result?

The server redirects to a port 80 and protocol (http) instead of https and port 27016 

#### Logs from VLC

```
http debug: outgoing request:
GET /033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791/channel.m3u8?t=userName-18b9286f0c5c813b5a133f3f7daed083 HTTP/1.1
Host: my.domain.com:27016 
Accept: */*
Accept-Language: en_US
User-Agent: VLC/3.0.16 LibVLC/3.0.16
Range: bytes=0-

http debug: incoming response:

HTTP/1.1 302 Found
Server: nginx/1.18.0
Date: Wed, 08 Dec 2021 08:11:42 GMT
Content-Length: 0
Connection: keep-alive
Location: http://my.domain.com/033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791/?t=userName-18b9286f0c5c813b5a133f3f7daed083

main debug: no access modules matched
main debug: redirecting to: http://my.domain.com/033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791/?t=userName-18b9286f0c5c813b5a133f3f7daed083
main debug: creating access: http://my.domain.com/033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791/?t=userName-18b9286f0c5c813b5a133f3f7daed083
main debug:  (path: \\my.domain.com\033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791\)
main debug: looking for access module matching "http": 27 candidates
http debug: resolving my.domain.com ...

http debug: outgoing request:
GET /033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791/?t=userName-18b9286f0c5c813b5a133f3f7daed083 HTTP/1.1
Host: my.domain.com
Accept: */*
Accept-Language: en_US
User-Agent: VLC/3.0.16 LibVLC/3.0.16
Range: bytes=0-

http debug: connection failed
access error: HTTP connection failure
http debug: querying proxy for http://my.domain.com/033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791/?t=userName-18b9286f0c5c813b5a133f3f7daed083
http debug: no proxy
http debug: http: server='my.domain.com' port=80 file='/033ba2cb26837dc299e54122f8e491a9592ab6e222ca895ebb6d20a2f0c7c791/'
main debug: net: connecting to my.domain.com port 80
main error: connection failed: Connection refused by peer
http error: cannot connect to my.domain.com:80
```

#### Logs from iptv-proxy

```
08.12.2021 08:03:30 [INFO ] :: IptvUser :: [userName] user created
08.12.2021 08:03:30 [INFO ] :: IptvServerChannel :: [userName] channel acquired: <Channel Name> / default
08.12.2021 08:03:31 [INFO ] :: IptvServerChannel :: [userName] channel released: <Channel Name> / default
08.12.2021 08:03:31 [INFO ] :: IptvUser :: [userName] user removed
```

**Comment by kvaster** [comment]
So... You're using nginx as a https frontend ? Can you please share your nginx config and 'base_url' setting from iptv config ?

**Comment by kvaster** [comment]
iptv-proxy should now how to form urls (they must be absolute) for clients.
Setting up iptv-proxy may be in two ways:

1) Direct use
In this case host is usually set to `0.0.0.0` with some port (`8080` for example).
Base url is formed in following way:
* use `base_url` setting from iptv-proxy config (i.e. `base_url: http://iptv.mydomain.com:8080`) if set
* use request scheme with host and port from request

such requests will not use TLS, cause using certificates is not implemented in iptv-proxy for now. It's easy to implement, but I think there is no need for this.

2) With frontend (i.e. nginx)

In this case host in iptv-proxy config is set to `127.0.0.1` usually and you have two choices:
* set up base_url properly, cause there is no way to determin automatically request url/port by default
* set up special 'Forwarded' header in nginx

For forwarded setup you should setup pass in iptv-proxy config: `forwarded_pass: xxxxx`
After that you should modify headers for proxy requests in nginx:

```
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Forwarded "pass=xxxxx;baseUrl=https://$host";
    }
```

Complete example:

```
server {
    listen 443 ssl;
    server_name iptv.somedomain.com;

    #access_log /var/log/nginx/iptv.access_log;

    root /var/www/iptv;

    proxy_read_timeout 15s;
    proxy_send_timeout 15s;

    client_header_timeout 15s;
    client_body_timeout 15s;
    send_timeout 15s;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Forwarded "pass=xxxxx;baseUrl=https://$host";

        keepalive_timeout 0;
    }
}
```

**Comment by reinthal** [comment]
Wow Thank you for swift answer!I found the error, and you are correct. I wasnt setting the baseURL in the reverse proxy. I incorrectly assumed I wouldn't have to specify it twice. But I guess that design choice is more elegant. Better separation of concern. I ended up using tvheadend instead, but its very feature heavy for just proxying a connection.

**Comment by kvaster** [comment]
I was using tvheadend long before, but it's design is for DVB. tvheadnend always wanted to scan my channels for EPG.
