### ISSUE TITLE
Question on use

### ISSUE THREAD

**Issue by adrianmihalko** [kvaster/iptv-proxy#8]
My situation: provider allows only 1client/1stream and I have 1 playlist only, which is not problem, but I want to share these streams to 3 more TV in my house:

<img width="447" alt="Screenshot 2022-01-17 at 19 15 37" src="https://user-images.githubusercontent.com/733361/149822192-d8c90db4-ed0e-4280-9f8e-bf1983f83c44.png">

I would like to achieve that if any of subclient or mainclient is watching others should be blocked from connecting (first come first serve). This way provider always see one connection/request and I am not breaking the rules.

In an advanced scenario I could imagine to stream to other clients a video with message "stream in use, try later" while the connection is busy.

Is this possible with this software?

**Comment by kvaster** [comment]
Currently iptv-proxy doesn't support this mode. It's on the TODO list. But generally this feature is not so usefull, cause different iptv clients may behave in different ways. Kodi's iptv.simple may fallback from live tv to 'catchup' stream and it will be hard to implement such logic.

**Comment by adrianmihalko** [comment]
Thanks. I installed the proxy, it works, but there are some questions.

My biggest problem is that the order of the channels are not the same as with my original m3u playlist (I am editing with m3u4u.com and using groups as folder and editing channel ordering manually). In apps they are now sorted by name A-Z. With original.m3u I have same order as I did on m3u4u.com:

**Original:**

#EXTM3U url-tvg=""
#EXTINF:-1 tvg-id="BBCOne.uk" tvg-name="BBC One" tvg-logo="s17153_dark_360w_270h.png" group-title="English",BBC One
http://localhost/1114.ts
#EXTINF:-1 tvg-id="BBCOne.uk" tvg-name="BBC One HD" tvg-logo="s17153_dark_360w_270h.png" group-title="English",BBC One HD
http://localhost/1158.ts

**Proxy:**

```
#EXTM3U
#EXTINF:0 tvg-id="362a9c117419082290546b99778c52b1" tvg-logo="s17153_dark_360w_270h.png",BBC One
#EXTGRP:English
http://192.168.1.155:9980/.../channel.m3u8?t=1643154416559-eb4f634...
#EXTINF:0 tvg-id="eab4f1909b0a99b616e771e9ee02c537" tvg-logo="s24353_dark_360w_270h.png",BBC One East Midland
#EXTGRP:English
http://192.168.1.155:9980/.../channel.m3u8?t=1643154416559-eb4f634...
#EXTINF:0 tvg-id="eab4f1909b0a99b616e771e9ee02c537" tvg-logo="s24353_dark_360w_270h.png",BBC One East Midlands
#EXTGRP:English
http://192.168.1.155:9980/.../channel.m3u8?t=1643154416559-eb4f634...
#EXTINF:0 tvg-id="362a9c117419082290546b99778c52b1" tvg-logo="s17153_dark_360w_270h.png",BBC One HD
```

Second problem is that I see a lot less channels with iptv-proxy:

![Screenshot 2022-01-26 at 01 14 04@2x](https://user-images.githubusercontent.com/733361/151081901-b2724f28-68a2-4135-b434-335d91598495.png)

I see no error in the log. Maybe there are duplicates and proxy is trying to remove them (it should not by default)?

**Comment by kvaster** [comment]
1. Ordering is not preserved for now - I will add option to preserve ordering.
2. Can you please send your m3u playlist (please remove any sensitive information like passwords from it) ?

**Comment by adrianmihalko** [comment]
1. That would be really great.
2. [Here](https://gist.githubusercontent.com/adrianmihalko/8f193c65c740d533eb6282853a0f37ea/raw/424b2370f0f3940d288c4ba47bcf8484223ab060/m3u) you go.

**Comment by kvaster** [comment]
The problem is with channels identification. i.e.:

```
#EXTINF:-1 tvg-id="CartoonNetwork.uk" tvg-name="CartoonNetwork" tvg-logo="http://schedulesdirect-api20141201-logos.s3.amazonaws.com/stationLogos/s78843_dark_360w_270h.png" group-title="English",CartoonNetwork
#EXTINF:-1 tvg-id="CartoonNetwork.uk" tvg-name="CartoonNetwork" tvg-logo="http://schedulesdirect-api20141201-logos.s3.amazonaws.com/stationLogos/s78843_dark_360w_270h.png" group-title="English",CartoonNetwork
```

Playlist contains channels with same names and ids and there is no proper way to combine channels in such case...
